name: CI do Windows

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instalar o Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Instalar as dependências
        run: npm install

      - name: Executar o arquivo index.js
        run: |
          node index.js
